<a href="https://colab.research.google.com/github/Shahilasulthana/TensorFlow/blob/main/Arithmetic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
#
# Write a TensorFlow program that:
# • Create two tensors, perform and print the results of the following operations:
# o Addition (A + B)
# o Subtraction (A - B)
# o Element-wise multiplication (A * B)
# o Element-wise division (A / B)
# o Element-wise exponentiation (A ** 2)
#

In [4]:
tensor_a = tf.constant([1,2,3,4,5])
tensor_b = tf.constant([10,20,30,40,50])
print("Tensor_a", tensor_a)
print("Tensor_b", tensor_b)
# arithmetic operations
print("\nAddition", tf.add(tensor_a, tensor_b))
print("\nSubtraction", tf.subtract(tensor_a, tensor_b))
print("\nMultiplication", tf.multiply(tensor_a, tensor_b))
print("\nDivision", tf.divide(tensor_a, tensor_b))
print("\nExponentiation of tensor_a", tf.pow(tensor_a, 2))
print("\nExponentiation of tensor_b",tf.pow(tensor_b,2))

Tensor_a tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Tensor_b tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)

Addition tf.Tensor([11 22 33 44 55], shape=(5,), dtype=int32)

Subtraction tf.Tensor([ -9 -18 -27 -36 -45], shape=(5,), dtype=int32)

Multiplication tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)

Division tf.Tensor([0.1 0.1 0.1 0.1 0.1], shape=(5,), dtype=float64)

Exponentiation of tensor_a tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)

Exponentiation of tensor_b tf.Tensor([ 100  400  900 1600 2500], shape=(5,), dtype=int32)
