<a href="https://colab.research.google.com/github/Shahilasulthana/TensorFlow/blob/main/Basics_summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

# Creating a 2x3 tensor of random integers between 0 and 10
tensor = tf.random.uniform(shape=(2,3), minval=0, maxval=10, dtype=tf.int32)
print("Original Tensor:")
print("Values:\n", tensor.numpy())
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# Reshaping to 3x2
tensor = tf.reshape(tensor, shape=(3,2))
print("\nAfter Reshape to 3x2:")
print("Values:\n", tensor.numpy())
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# Converting to float32tensor = tf.cast(tensor, dtype=tf.float32)
print("\nAfter Converting to float32:")
print("Values:\n", tensor.numpy())
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())

# Adding 0.5 to all elements
tensor = tf.add(tensor, 0.5)
print("\nAfter Adding 0.5:")
print("Values:\n", tensor.numpy())
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Rank:", tf.rank(tensor).numpy())



Original Tensor:
Values:
 [[2 4 4]
 [6 4 2]]
Shape: (2, 3)
Dtype: <dtype: 'int32'>
Rank: 2

After Reshape to 3x2:
Values:
 [[2 4]
 [4 6]
 [4 2]]
Shape: (3, 2)
Dtype: <dtype: 'int32'>
Rank: 2

After Converting to float32:
Values:
 [[2. 4.]
 [4. 6.]
 [4. 2.]]
Shape: (3, 2)
Dtype: <dtype: 'float32'>
Rank: 2

After Adding 0.5:
Values:
 [[2.5 4.5]
 [4.5 6.5]
 [4.5 2.5]]
Shape: (3, 2)
Dtype: <dtype: 'float32'>
Rank: 2
