<a href="https://colab.research.google.com/github/Shahilasulthana/TensorFlow/blob/main/Matrix_multiplications.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
# 2. Matrix Multiplication:
# Write a TensorFlow program that:
# • Creates two compatible 2D tensors
# o The 1-D tensor from Task 1 into a 2×3 tensor (observe any error, handle it).
# o The 2-D tensor into shape (2,3).
# o The 3-D tensor into a 2×6 matrix.
# • Performs matrix multiplication using:
# o tf.matmul(M1, M2)
# o tf.linalg.matmul(M1, M2) (to observe any differences)
# • Displays the result and its shape.

In [4]:
tensor_1d = tf.constant([1, 2, 3, 4, 5, 6])
tensor_2d = tf.constant([[7, 8, 9], [10, 11, 12]])
tensor_3d = tf.constant([[[1, 2], [3, 4], [5, 6]],
                         [[7, 8], [9, 10], [11, 12]]])
print("tensor_1d\n",tensor_1d)
print("tensor_2d\n",tensor_2d)
print("tensor_3d\n",tensor_3d)

tensor_1d
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tensor_2d
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
tensor_3d
 tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32)


In [5]:
try:
    reshaped_1d = tf.reshape(tensor_1d, (2, 3))
    print("\n1D reshaped to (2, 3):\n", reshaped_1d)
except tf.errors.InvalidArgumentError as e:
    print("Error reshaping 1D tensor:", e)


1D reshaped to (2, 3):
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
reshaped_2d = tf.reshape(tensor_2d,(3,2))
print("Reshaped_2d_Tensor is", reshaped_2d)



Reshaped_2d_Tensor is tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [8]:
reshaped_3d = tf.reshape(tensor_3d,(2,6))
print("Reshaped_3d_tensor is", reshaped_3d)

Reshaped_3d_tensor is tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [9]:
tensor_matmul = tf.matmul(reshaped_1d, reshaped_2d)
print("Matmul result of tensor_1d and tensor_2d is", tensor_matmul)

Matmul result of tensor_1d and tensor_2d is tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [10]:
tensor_linmatmul = tf.linalg.matmul(reshaped_1d, reshaped_2d)
print("Matmul result of tensor_1d and tensor_2d is", tensor_linmatmul)

Matmul result of tensor_1d and tensor_2d is tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
