<a href="https://colab.research.google.com/github/Shahilasulthana/TensorFlow/blob/main/Tensor_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Create a 3×3 tensor of integers
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Tensor:")
print(tensor.numpy())

# First row
first_row = tensor[0]
print("\nFirst Row:")
print(first_row.numpy())

# Second row
second_row = tensor[1]
print("\nSecond Row:")
print(second_row.numpy())

# Bottom-right element (row 2, col 2)
bottom_right = tensor[2, 2]
print("\nBottom-right Element:")
print(bottom_right.numpy())

# 2×2 submatrix (top-left corner)
submatrix = tensor[0:2, 0:2]
print("\n2×2 Submatrix (Top-left):")
print(submatrix.numpy())


Original Tensor:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

First Row:
[1 2 3]

Second Row:
[4 5 6]

Bottom-right Element:
9

2×2 Submatrix (Top-left):
[[1 2]
 [4 5]]
