In [ ]:
# Installed tensorflow version 2.18.0
import tensorflow as tf
print("TensorFlow version:",tf.__version__)

TensorFlow version: 2.18.0


In [ ]:
def information(tensor, name):
  print(name)
  print("\n Value:", tensor.numpy())
  print("Shape:", tensor.shape)
  print("DataType:", tensor.dtype)
  print("Rank:", tf.rank(tensor))
  print("Size:", tf.size(tensor))



In [ ]:
# A scalar (0-D tensor) with an integer value.

scalar = tf.constant(52)
information(scalar, "scalar(0-D tensor)")


scalar(0-D tensor)

 Value: 52
Shape: ()
DataType: <dtype: 'int32'>
Rank: tf.Tensor(0, shape=(), dtype=int32)
Size: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# A vector (1-D tensor) with 5 elements.

vector = tf.constant([10, 20, 30, 40, 50])
information(vector,"vector(1-D tensor)")

vector(1-D tensor)

 Value: [10 20 30 40 50]
Shape: (5,)
DataType: <dtype: 'int32'>
Rank: tf.Tensor(1, shape=(), dtype=int32)
Size: tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# A matrix (2-D tensor) of size 3×2.

matrix = tf.constant([[10,2], [20,4], [30,6]])
information(matrix, "matrix(2-D) tensor")

matrix(2-D) tensor

 Value: [[10  2]
 [20  4]
 [30  6]]
Shape: (3, 2)
DataType: <dtype: 'int32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
  # A 3-D tensor of shape 2×2×3.

  tensor_3d = tf.constant([
      [[1, 2, 3],
      [4, 5, 6]],
      [[7, 8, 9],
      [10, 11, 12]]
  ])
  information(tensor_3d, "3-D Tensor (2×2×3)")

3-D Tensor (2×2×3)

 Value: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
DataType: <dtype: 'int32'>
Rank: tf.Tensor(3, shape=(), dtype=int32)
Size: tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
# 3×3 tensor filled with zeros

tensor_0 = tf.zeros([3, 3])
information(tensor_0, "3×3 tensor with all zeroes")

3×3 tensor with all zeroes

 Value: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)
DataType: <dtype: 'float32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
# A 2×4 tensor filled with ones.

tensor_1 = tf.ones([2,4])
information(tensor_1, "2x4 tensor with all ones")

2x4 tensor with all ones

 Value: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (2, 4)
DataType: <dtype: 'float32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# A 2×2×2 tensor filled with a constant (e.g., 7).

tensor_const = tf.fill([2,2,2], 7)
information(tensor_const,"2x2x2 tensor with all 7")

2x2x2 tensor with all 7

 Value: [[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
Shape: (2, 2, 2)
DataType: <dtype: 'int32'>
Rank: tf.Tensor(3, shape=(), dtype=int32)
Size: tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# A 3×3 tensor of random normal values (mean 0, stddev 1).

tensor_random = tf.random.normal(shape = [3,3], mean=0, stddev=1)
information(tensor_random,"A 3×3 tensor of random normal values with (mean 0, stddev 1)")

A 3×3 tensor of random normal values with (mean 0, stddev 1)

 Value: [[ 1.2225748  -0.20275645  1.2880249 ]
 [ 0.53541607 -0.27951944 -0.960105  ]
 [ 0.12129392 -0.00987377  0.7935276 ]]
Shape: (3, 3)
DataType: <dtype: 'float32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
# 2×3 tensor of random uniform values between 0 and 10

uniform_tensor = tf.random.uniform(shape=[2, 3], minval=0, maxval=10)
information(uniform_tensor, "2×3 Tensor with Random Uniform Values (0-10)")

2×3 Tensor with Random Uniform Values (0-10)

 Value: [[7.0263696 2.393608  3.528105 ]
 [8.3014145 3.1526673 0.8182752]]
Shape: (2, 3)
DataType: <dtype: 'float32'>
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(6, shape=(), dtype=int32)
